// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/game.proto

package gamepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientHello is sent when a client first connects
type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // Client version for compatibility
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ClientHello) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *ClientHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ServerWelcome is the server's response to ClientHello
type ServerWelcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TickRate      uint32                 `protobuf:"varint,2,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`       // Server tick rate (e.g., 60)
	ServerTime    uint64                 `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // Server timestamp in ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerWelcome) Reset() {
	*x = ServerWelcome{}
	mi := &file_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerWelcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerWelcome) ProtoMessage() {}

func (x *ServerWelcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerWelcome.ProtoReflect.Descriptor instead.
func (*ServerWelcome) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *ServerWelcome) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ServerWelcome) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *ServerWelcome) GetServerTime() uint64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// Vec2 is a 2D vector for positions and velocities
type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *Vec2) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// PlayerInput represents input from a client
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`   // Sequence number for ordering
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Client timestamp
	Movement      *Vec2                  `protobuf:"bytes,3,opt,name=movement,proto3" json:"movement,omitempty"`    // Movement direction (-1 to 1)
	Jump          bool                   `protobuf:"varint,4,opt,name=jump,proto3" json:"jump,omitempty"`
	Action_1      bool                   `protobuf:"varint,5,opt,name=action_1,json=action1,proto3" json:"action_1,omitempty"` // Generic action buttons
	Action_2      bool                   `protobuf:"varint,6,opt,name=action_2,json=action2,proto3" json:"action_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerInput) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PlayerInput) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PlayerInput) GetMovement() *Vec2 {
	if x != nil {
		return x.Movement
	}
	return nil
}

func (x *PlayerInput) GetJump() bool {
	if x != nil {
		return x.Jump
	}
	return false
}

func (x *PlayerInput) GetAction_1() bool {
	if x != nil {
		return x.Action_1
	}
	return false
}

func (x *PlayerInput) GetAction_2() bool {
	if x != nil {
		return x.Action_2
	}
	return false
}

// PlayerState is the server's view of a player
type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Vec2                  `protobuf:"bytes,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Rotation      float32                `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerState) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerState) GetVelocity() *Vec2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *PlayerState) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *PlayerState) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GameStateSnapshot is the full game state (sent on join/reconnect)
type GameStateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"` // Future: game objects, items, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateSnapshot) Reset() {
	*x = GameStateSnapshot{}
	mi := &file_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateSnapshot) ProtoMessage() {}

func (x *GameStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateSnapshot.ProtoReflect.Descriptor instead.
func (*GameStateSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameStateSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *GameStateSnapshot) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GameStateSnapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

// GameStateDelta contains only changes since last tick
type GameStateDelta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tick           uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Timestamp      uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChangedPlayers []*PlayerState         `protobuf:"bytes,3,rep,name=changed_players,json=changedPlayers,proto3" json:"changed_players,omitempty"`
	RemovedPlayers []string               `protobuf:"bytes,4,rep,name=removed_players,json=removedPlayers,proto3" json:"removed_players,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GameStateDelta) Reset() {
	*x = GameStateDelta{}
	mi := &file_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateDelta) ProtoMessage() {}

func (x *GameStateDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateDelta.ProtoReflect.Descriptor instead.
func (*GameStateDelta) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameStateDelta) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *GameStateDelta) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GameStateDelta) GetChangedPlayers() []*PlayerState {
	if x != nil {
		return x.ChangedPlayers
	}
	return nil
}

func (x *GameStateDelta) GetRemovedPlayers() []string {
	if x != nil {
		return x.RemovedPlayers
	}
	return nil
}

// PlayerJoin broadcast when a player joins
type PlayerJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerState           `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoin) Reset() {
	*x = PlayerJoin{}
	mi := &file_proto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoin) ProtoMessage() {}

func (x *PlayerJoin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoin.ProtoReflect.Descriptor instead.
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerJoin) GetPlayer() *PlayerState {
	if x != nil {
		return x.Player
	}
	return nil
}

// PlayerLeave broadcast when a player leaves
type PlayerLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeave) Reset() {
	*x = PlayerLeave{}
	mi := &file_proto_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeave) ProtoMessage() {}

func (x *PlayerLeave) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeave.ProtoReflect.Descriptor instead.
func (*PlayerLeave) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerLeave) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerLeave) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Message is the top-level envelope for all messages
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_ClientHello
	//	*Message_ServerWelcome
	//	*Message_PlayerInput
	//	*Message_StateSnapshot
	//	*Message_StateDelta
	//	*Message_PlayerJoin
	//	*Message_PlayerLeave
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*Message_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *Message) GetServerWelcome() *ServerWelcome {
	if x != nil {
		if x, ok := x.Payload.(*Message_ServerWelcome); ok {
			return x.ServerWelcome
		}
	}
	return nil
}

func (x *Message) GetPlayerInput() *PlayerInput {
	if x != nil {
		if x, ok := x.Payload.(*Message_PlayerInput); ok {
			return x.PlayerInput
		}
	}
	return nil
}

func (x *Message) GetStateSnapshot() *GameStateSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Message_StateSnapshot); ok {
			return x.StateSnapshot
		}
	}
	return nil
}

func (x *Message) GetStateDelta() *GameStateDelta {
	if x != nil {
		if x, ok := x.Payload.(*Message_StateDelta); ok {
			return x.StateDelta
		}
	}
	return nil
}

func (x *Message) GetPlayerJoin() *PlayerJoin {
	if x != nil {
		if x, ok := x.Payload.(*Message_PlayerJoin); ok {
			return x.PlayerJoin
		}
	}
	return nil
}

func (x *Message) GetPlayerLeave() *PlayerLeave {
	if x != nil {
		if x, ok := x.Payload.(*Message_PlayerLeave); ok {
			return x.PlayerLeave
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_ClientHello struct {
	// Connection
	ClientHello *ClientHello `protobuf:"bytes,1,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type Message_ServerWelcome struct {
	ServerWelcome *ServerWelcome `protobuf:"bytes,2,opt,name=server_welcome,json=serverWelcome,proto3,oneof"`
}

type Message_PlayerInput struct {
	// Input
	PlayerInput *PlayerInput `protobuf:"bytes,10,opt,name=player_input,json=playerInput,proto3,oneof"`
}

type Message_StateSnapshot struct {
	// State
	StateSnapshot *GameStateSnapshot `protobuf:"bytes,20,opt,name=state_snapshot,json=stateSnapshot,proto3,oneof"`
}

type Message_StateDelta struct {
	StateDelta *GameStateDelta `protobuf:"bytes,21,opt,name=state_delta,json=stateDelta,proto3,oneof"`
}

type Message_PlayerJoin struct {
	// Events
	PlayerJoin *PlayerJoin `protobuf:"bytes,30,opt,name=player_join,json=playerJoin,proto3,oneof"`
}

type Message_PlayerLeave struct {
	PlayerLeave *PlayerLeave `protobuf:"bytes,31,opt,name=player_leave,json=playerLeave,proto3,oneof"`
}

func (*Message_ClientHello) isMessage_Payload() {}

func (*Message_ServerWelcome) isMessage_Payload() {}

func (*Message_PlayerInput) isMessage_Payload() {}

func (*Message_StateSnapshot) isMessage_Payload() {}

func (*Message_StateDelta) isMessage_Payload() {}

func (*Message_PlayerJoin) isMessage_Payload() {}

func (*Message_PlayerLeave) isMessage_Payload() {}

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\x04game\"e\n" +
	"\vClientHello\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"j\n" +
	"\rServerWelcome\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\ttick_rate\x18\x02 \x01(\rR\btickRate\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x04R\n" +
	"serverTime\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"\xb9\x01\n" +
	"\vPlayerInput\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12&\n" +
	"\bmovement\x18\x03 \x01(\v2\n" +
	".game.Vec2R\bmovement\x12\x12\n" +
	"\x04jump\x18\x04 \x01(\bR\x04jump\x12\x19\n" +
	"\baction_1\x18\x05 \x01(\bR\aaction1\x12\x19\n" +
	"\baction_2\x18\x06 \x01(\bR\aaction2\"\xb4\x01\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12&\n" +
	"\bposition\x18\x02 \x01(\v2\n" +
	".game.Vec2R\bposition\x12&\n" +
	"\bvelocity\x18\x03 \x01(\v2\n" +
	".game.Vec2R\bvelocity\x12\x1a\n" +
	"\brotation\x18\x04 \x01(\x02R\brotation\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\"r\n" +
	"\x11GameStateSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12+\n" +
	"\aplayers\x18\x03 \x03(\v2\x11.game.PlayerStateR\aplayers\"\xa7\x01\n" +
	"\x0eGameStateDelta\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12:\n" +
	"\x0fchanged_players\x18\x03 \x03(\v2\x11.game.PlayerStateR\x0echangedPlayers\x12'\n" +
	"\x0fremoved_players\x18\x04 \x03(\tR\x0eremovedPlayers\"7\n" +
	"\n" +
	"PlayerJoin\x12)\n" +
	"\x06player\x18\x01 \x01(\v2\x11.game.PlayerStateR\x06player\"B\n" +
	"\vPlayerLeave\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xaa\x03\n" +
	"\aMessage\x126\n" +
	"\fclient_hello\x18\x01 \x01(\v2\x11.game.ClientHelloH\x00R\vclientHello\x12<\n" +
	"\x0eserver_welcome\x18\x02 \x01(\v2\x13.game.ServerWelcomeH\x00R\rserverWelcome\x126\n" +
	"\fplayer_input\x18\n" +
	" \x01(\v2\x11.game.PlayerInputH\x00R\vplayerInput\x12@\n" +
	"\x0estate_snapshot\x18\x14 \x01(\v2\x17.game.GameStateSnapshotH\x00R\rstateSnapshot\x127\n" +
	"\vstate_delta\x18\x15 \x01(\v2\x14.game.GameStateDeltaH\x00R\n" +
	"stateDelta\x123\n" +
	"\vplayer_join\x18\x1e \x01(\v2\x10.game.PlayerJoinH\x00R\n" +
	"playerJoin\x126\n" +
	"\fplayer_leave\x18\x1f \x01(\v2\x11.game.PlayerLeaveH\x00R\vplayerLeaveB\t\n" +
	"\apayloadB8Z6github.com/LemmyAI/gameserver/internal/protocol/gamepbb\x06proto3"

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData []byte
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)))
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_game_proto_goTypes = []any{
	(*ClientHello)(nil),       // 0: game.ClientHello
	(*ServerWelcome)(nil),     // 1: game.ServerWelcome
	(*Vec2)(nil),              // 2: game.Vec2
	(*PlayerInput)(nil),       // 3: game.PlayerInput
	(*PlayerState)(nil),       // 4: game.PlayerState
	(*GameStateSnapshot)(nil), // 5: game.GameStateSnapshot
	(*GameStateDelta)(nil),    // 6: game.GameStateDelta
	(*PlayerJoin)(nil),        // 7: game.PlayerJoin
	(*PlayerLeave)(nil),       // 8: game.PlayerLeave
	(*Message)(nil),           // 9: game.Message
}
var file_proto_game_proto_depIdxs = []int32{
	2,  // 0: game.PlayerInput.movement:type_name -> game.Vec2
	2,  // 1: game.PlayerState.position:type_name -> game.Vec2
	2,  // 2: game.PlayerState.velocity:type_name -> game.Vec2
	4,  // 3: game.GameStateSnapshot.players:type_name -> game.PlayerState
	4,  // 4: game.GameStateDelta.changed_players:type_name -> game.PlayerState
	4,  // 5: game.PlayerJoin.player:type_name -> game.PlayerState
	0,  // 6: game.Message.client_hello:type_name -> game.ClientHello
	1,  // 7: game.Message.server_welcome:type_name -> game.ServerWelcome
	3,  // 8: game.Message.player_input:type_name -> game.PlayerInput
	5,  // 9: game.Message.state_snapshot:type_name -> game.GameStateSnapshot
	6,  // 10: game.Message.state_delta:type_name -> game.GameStateDelta
	7,  // 11: game.Message.player_join:type_name -> game.PlayerJoin
	8,  // 12: game.Message.player_leave:type_name -> game.PlayerLeave
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	file_proto_game_proto_msgTypes[9].OneofWrappers = []any{
		(*Message_ClientHello)(nil),
		(*Message_ServerWelcome)(nil),
		(*Message_PlayerInput)(nil),
		(*Message_StateSnapshot)(nil),
		(*Message_StateDelta)(nil),
		(*Message_PlayerJoin)(nil),
		(*Message_PlayerLeave)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
